name: orderflow

services:
  inventory-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: inventory
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory -d inventory_db"]
      interval: 5s
      timeout: 3s
      retries: 15

  order-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
    volumes:
      - order-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orders -d order_db"]
      interval: 5s
      timeout: 3s
      retries: 15

  inventory-service:
    build: ./inventory-service
    environment:
      INVENTORY_DB_URL: jdbc:postgresql://inventory-db:5432/inventory_db
      INVENTORY_DB_USER: inventory
      INVENTORY_DB_PASSWORD: inventory
    ports:
      - "8081:8081"
    depends_on:
      inventory-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 4s
      retries: 15
      start_period: 45s

  order-service:
    build: ./order-service
    environment:
      ORDER_DB_URL: jdbc:postgresql://order-db:5432/order_db
      ORDER_DB_USER: orders
      ORDER_DB_PASSWORD: orders
      INVENTORY_BASE_URL: http://inventory-service:8081
    ports:
      - "8080:8080"
    depends_on:
      order-db:
        condition: service_healthy
      inventory-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 4s
      retries: 15
      start_period: 45s

  web:
    build: ./frontend
    environment:
      PORT: "80"
      PROXY_SCHEME: http
      INVENTORY_UPSTREAM_HOST: inventory-service:8081
      ORDER_UPSTREAM_HOST: order-service:8080
    ports:
      - "8088:80"
    depends_on:
      inventory-service:
        condition: service_healthy
      order-service:
        condition: service_healthy

volumes:
  inventory-db-data:
  order-db-data:
