-- Inventory Service schema (own database: inventory_db)
--
-- Concurrency model:
--   * The reserve path never does read-then-write in application code. It issues a single
--     conditional UPDATE ( ... WHERE available_quantity >= :qty ). PostgreSQL takes a row
--     lock for the duration of that statement, so concurrent reservations for the same SKU
--     serialize and the guard is always evaluated against a committed value.
--   * The CHECK constraints below are a hard floor: even a logic bug cannot drive stock
--     negative -- the database rejects the write.
--   * "version" backs JPA optimistic locking for the admin restock/adjust path, which does
--     go read-modify-write through the entity.

CREATE TABLE inventory_item (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku                VARCHAR(64)  NOT NULL,
    name               VARCHAR(255) NOT NULL,
    available_quantity INTEGER      NOT NULL,
    reserved_quantity  INTEGER      NOT NULL DEFAULT 0,
    version            BIGINT       NOT NULL DEFAULT 0,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT uq_inventory_item_sku      UNIQUE (sku),
    CONSTRAINT ck_inventory_available_nonneg CHECK (available_quantity >= 0),
    CONSTRAINT ck_inventory_reserved_nonneg  CHECK (reserved_quantity >= 0)
);

CREATE TABLE reservation (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id UUID         NOT NULL,
    status         VARCHAR(16)  NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    expires_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_reservation_reservation_id UNIQUE (reservation_id),
    CONSTRAINT ck_reservation_status CHECK (status IN ('CONFIRMED', 'COMMITTED', 'RELEASED'))
);

CREATE TABLE reservation_line (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_fk BIGINT       NOT NULL REFERENCES reservation (id) ON DELETE CASCADE,
    sku            VARCHAR(64)  NOT NULL,
    quantity       INTEGER      NOT NULL,
    CONSTRAINT ck_reservation_line_qty_positive CHECK (quantity > 0)
);

CREATE INDEX idx_reservation_line_reservation ON reservation_line (reservation_fk);
CREATE INDEX idx_reservation_status_expires   ON reservation (status, expires_at);
