-- Order Service schema (own database: order_db)
--
-- No foreign keys point at the Inventory Service. `reservation_id` is the correlation key
-- passed to Inventory when holding stock; it is also the idempotency key that makes a
-- retried reservation call safe.

CREATE SEQUENCE order_number_seq START WITH 1000 INCREMENT BY 1;

CREATE TABLE orders (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number     VARCHAR(32)   NOT NULL,
    reservation_id   UUID          NOT NULL,
    customer_id      VARCHAR(64)   NOT NULL,
    status           VARCHAR(16)   NOT NULL,
    rejection_reason VARCHAR(512),
    total_amount     NUMERIC(12, 2) NOT NULL,
    version          BIGINT        NOT NULL DEFAULT 0,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT uq_orders_order_number   UNIQUE (order_number),
    CONSTRAINT uq_orders_reservation_id UNIQUE (reservation_id),
    CONSTRAINT ck_orders_status CHECK (status IN ('PLACED', 'CONFIRMED', 'SHIPPED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT ck_orders_total_nonneg CHECK (total_amount >= 0)
);

CREATE TABLE order_item (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_fk   BIGINT        NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    sku        VARCHAR(64)   NOT NULL,
    quantity   INTEGER       NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    CONSTRAINT ck_order_item_qty_positive CHECK (quantity > 0),
    CONSTRAINT ck_order_item_price_nonneg CHECK (unit_price >= 0)
);

CREATE INDEX idx_order_item_order ON order_item (order_fk);
CREATE INDEX idx_orders_customer  ON orders (customer_id);
CREATE INDEX idx_orders_status    ON orders (status);
